name: Auto Delete Branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
    steps:
      - name: Delete merged branch
        uses: fast-flow/github-action-delete-branch@v1
        with:
          branch_name: ${{ github.event.pull_request.head.ref }}
