name: Auto Delete Branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-merged-branch:
    runs-on: ubuntu-latest
    # This job only runs if the pull request was merged
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git for PAT authentication
        run: git config --global url."https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Delete merged branch
        run: git push origin --delete ${{ github.event.pull_request.head.ref }}
