name: Auto Delete Branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    # This job only runs if the pull request was merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      # Required for peter-evans/delete-branch to push the branch deletion
      contents: write
    steps:
      - name: Delete merged branch
        uses: peter-evans/delete-branch@v3
        with:
          # The name of the branch to be deleted
          branch: ${{ github.event.pull_request.head.ref }}
